### ISSUE TITLE
Panic when trying to play a specific album on my system

### ISSUE THREAD

**Issue by adamrdrew** [adamrdrew/mosh#29]
I think the problem this is either an album format we don't support and I'm not handling that OR this isn't an album at all. I fat fingered the ID and realized it afterward. Or maybe there's just nothing with that ID. Whatever it is we should handle it.

```
 $ mosh pl a 98587
panic: Post "http://127.0.0.1:9666/listener": EOF

goroutine 1 [running]:
github.com/adamrdrew/mosh/ipc.maybePanic(...)
        /home/addrew/Development/mosh/ipc/ipc.go:47
github.com/adamrdrew/mosh/ipc.daemonTransport({{0x8c7987, 0xb}, {0x7fff55401e65, 0x5}, {0x0, 0x0, 0x0}})
        /home/addrew/Development/mosh/ipc/ipc.go:65 +0x25b
github.com/adamrdrew/mosh/ipc.SendMessageToDaemon({{0x8c7987, 0xb}, {0x7fff55401e65, 0x5}, {0x0, 0x0, 0x0}})
        /home/addrew/Development/mosh/ipc/ipc.go:75 +0x5b
github.com/adamrdrew/mosh/cmd.glob..func13(0xdf9e80?, {0xc000075420, 0x1, 0x1?})
        /home/addrew/Development/mosh/cmd/play.go:36 +0xe5
github.com/spf13/cobra.(*Command).execute(0xdf9e80, {0xc0000753f0, 0x1, 0x1})
        /home/addrew/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xdfa380)
        /home/addrew/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/addrew/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/adamrdrew/mosh/cmd.Execute(...)
        /home/addrew/Development/mosh/cmd/root.go:16
main.main()
        /home/addrew/Development/mosh/mosh.go:12 +0x54
```

**Comment by adamrdrew** [comment]
This is what we're doing:

```
http://<plex>:<port>/library/metadata/98587/children?X-Plex-Token=<token>
```

And we're getting a 400 with:

```
<html><head><title>Bad Request</title></head><body><h1>400 Bad Request</h1></body></html>
```

So I think what's going on is that Plex just raises a 400 if it gets a request for children of an object that doesn't have children. I don't know what 98587 is on my server, but it could be a picture or a movie or who knows what. IDs are all in one big space. So, I guess we just need to handle 400 and do something graceful.

**Comment by adamrdrew** [comment]
Fixed in 

```
commit 54f095893bf7b34dd1b84d5c3848405c81cef753 (HEAD -> master, origin/master, origin/HEAD)
Author: Adam Drew <adamrdrew@live.com>
Date:   Fri May 27 13:12:29 2022 -0400

    Handle cases where daemon gets a 400 from plex
```

In a bunch of our calls to plex we now look at the response code and if its not 200 we return sane empty objects rather than panic.
