### ISSUE TITLE
Panics in http

### ISSUE THREAD

**Issue by adamrdrew** [adamrdrew/mosh#35]
```
goroutine 37 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/golang/src/net/http/server.go:1825 +0xbf
panic({0x878180, 0xc21010})
        /usr/lib/golang/src/runtime/panic.go:844 +0x258
github.com/adamrdrew/mosh/player.(*Player).GoForwardInQueue(0xc74340)
        /home/adamdrew/Development/mosh/player/player.go:200 +0x87
github.com/adamrdrew/mosh/moshd.handleMessage({{0xc0000242a8, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}})
        /home/adamdrew/Development/mosh/moshd/moshd.go:195 +0x1ba
github.com/adamrdrew/mosh/moshd.httpListener({0x9b2550, 0xc00061c000}, 0xc0000d0e00)
        /home/adamdrew/Development/mosh/moshd/moshd.go:162 +0x18d
net/http.HandlerFunc.ServeHTTP(0x856400?, {0x9b2550?, 0xc00061c000?}, 0xc0000920c0?)
        /usr/lib/golang/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x9b2550, 0xc00061c000}, 0xc0000d0e00)
        /usr/lib/golang/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0x9b0d88?}, {0x9b2550, 0xc00061c000}, 0xc0000d0e00)
        /usr/lib/golang/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0000b8000, {0x9b2988, 0xc0005fc630})
        /usr/lib/golang/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/lib/golang/src/net/http/server.go:3071 +0x4db
2022/06/09 09:17:44 Message recieved...
2022/06/09 09:17:44 Message recieved...
2022/06/09 09:17:50 Message recieved...
2022/06/09 09:17:50 http: panic serving 127.0.0.1:58832: runtime error: invalid memory address or nil pointer dereference
goroutine 66 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/golang/src/net/http/server.go:1825 +0xbf
panic({0x878180, 0xc21010})
        /usr/lib/golang/src/runtime/panic.go:844 +0x258
github.com/adamrdrew/mosh/player.(*Player).GetNowPlaying(0xc74340)
        /home/adamdrew/Development/mosh/player/player.go:93 +0xba
github.com/adamrdrew/mosh/moshd.handleMessage({{0xc0001a4110, 0xb}, {0x0, 0x0}, {0x0, 0x0, 0x0}})
        /home/adamdrew/Development/mosh/moshd/moshd.go:187 +0x3f8
github.com/adamrdrew/mosh/moshd.httpListener({0x9b2550, 0xc00061c000}, 0xc0000d0e00)
        /home/adamdrew/Development/mosh/moshd/moshd.go:162 +0x18d
net/http.HandlerFunc.ServeHTTP(0x856400?, {0x9b2550?, 0xc00061c000?}, 0xc0000920c0?)
        /usr/lib/golang/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x9b2550, 0xc00061c000}, 0xc0000d0e00)
        /usr/lib/golang/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0x9b0d88?}, {0x9b2550, 0xc00061c000}, 0xc0000d0e00)
        /usr/lib/golang/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0001d0140, {0x9b2988, 0xc0005fc630})
        /usr/lib/golang/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/lib/golang/src/net/http/server.go:3071 +0x4db
```

Symptom is play but no sound. Restarted the daemon. Play an album. No sound. Any attempt to interact with play queue (get status, next, previous) leads to panics in logs

**Comment by adamrdrew** [comment]
I think the problem is unsupported codec. I switched to a different album and it is working. Looked under /tmp/mosh and saw:

```
-rw-r-----. 1 adamdrew adamdrew 9159620 May 12 07:24 library-parts-78520-1574347805-file.m4a
-rw-r-----. 1 adamdrew adamdrew 6928469 May 12 07:24 library-parts-78521-1574347817-file.m4a
-rw-r-----. 1 adamdrew adamdrew 6056821 May 12 07:24 library-parts-78522-1574347819-file.m4a
-rw-r-----. 1 adamdrew adamdrew 9262656 May 12 07:24 library-parts-78523-1574347827-file.m4a
-rw-r-----. 1 adamdrew adamdrew 8659380 May 12 07:24 library-parts-78524-1574347826-file.m4a
-rw-r-----. 1 adamdrew adamdrew 9835687 Apr 14 07:10 library-parts-78525-1574347836-file.m4a
-rw-r-----. 1 adamdrew adamdrew 9102534 May 12 07:24 library-parts-78526-1574347832-file.m4a
-rw-r-----. 1 adamdrew adamdrew 7009092 May 12 07:24 library-parts-78527-1574347840-file.m4a
-rw-r-----. 1 adamdrew adamdrew 9158297 Apr 14 07:10 library-parts-78528-1574347848-file.m4a

```
